language: node_js

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.21.1-1

cache:
  yarn: true

install:
  - yarn --silent

script:
  - yarn run test
  - yarn run codecov -f coverage/*.json
  - yarn run lint

before_deploy:
  - yarn run build:docs
  - touch docs/.nojekyll

deploy:
  - provider: pages:git
    token: $GITHUB_TOKEN
    local_dir: docs
    cleanup: false
    edge: true
    on:
      tags: true

  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    cleanup: false
    edge: true
    on:
      tags: true
